### ISSUE TITLE
Forgot to mention how to read email reply in project

### ISSUE THREAD

**Issue by circuitmamu** [TIKAJHQ/tiket#1]
please give flow or eg. in which user can understand that if any reply comes then how to read email that received there

**Comment by eksha** [comment]
Hi @circuitmamu 

For reading the email reply, you will have to use a separate service, that 
1. Should listen for the mail content using an IMAP configuration.
2. Parse the mail into a format similar to the json string mentioned [here](https://github.com/tikajhq/tiket/blob/ff7ee29f1daddff27a48e44a3495548d47a8e926/application/controllers/API/Ticket.php#L124)
3. Hit the API end point which is at [/API/ticket/processIMAPEmail](https://github.com/tikajhq/tiket/blob/ff7ee29f1daddff27a48e44a3495548d47a8e926/application/controllers/API/Ticket.php#L109)

The method [here](https://github.com/tikajhq/tiket/blob/ff7ee29f1daddff27a48e44a3495548d47a8e926/application/models/ticket/Ticket_model.php#L216) will then further process the email content, and map as reply to any existing ticket thread or create a new ticket.

**Comment by eksha** [comment]
@circuitmamu I am closing the issue for now, do let me know if further assistance is required.
