### ISSUE TITLE
Do not send emails

### ISSUE THREAD

**Issue by ddiaz2380** [TIKAJHQ/tiket#12]
Configure both the client.config.php and config.product.php with the mail data using one of gmail and mailtrap in neither case it worked. Thanks greetings!

**Comment by eksha** [comment]
Hi!

Please uncomment the line of code at below locations to send update emails:

https://github.com/tikajhq/tiket/blob/master/application/models/ticket/Ticket_model.php#L154
https://github.com/tikajhq/tiket/blob/master/application/models/ticket/Ticket_model.php#L203

We had it commented, as this codebase was part of demo.

Hope this resolves your query.

**Comment by eksha** [comment]
@ddiaz2380 hope it resolved your query, closing this issue for now.
