### ISSUE TITLE
EROR

### ISSUE THREAD

**Issue by wissnusetiawan** [TIKAJHQ/tiket#2]
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/14894326/84962708-afd97780-b131-11ea-8dc0-ced8afd5a6fe.PNG">

**Comment by eksha** [comment]
Hi @wissnusetiawan 

It seems you have resolved the issue.
The solution would be to run `composer install` within the project root, it will create the vendor directory and the autoload.php script
I will update the installation instructions in readme, where I think this was missed out.
