### ISSUE TITLE
Cannot Email send after create ticket

### ISSUE THREAD

**Issue by wissnusetiawan** [TIKAJHQ/tiket#4]
hi how to change e-mail, so that it can be sent to our e-mail

**Comment by eksha** [comment]
Hi @wissnusetiawan 

There is a sample config file, where the configs are defined.
[Sample Config](https://github.com/tikajhq/tiket/blob/master/application/config/client.config.sample.php)

Below are the email settings in the file that you can tweak for the desired function
```
//Client Mail Settings
define('CLIENT_FROM_EMAIL', 'all@xxx.xx.co');
define('CLIENT_HELPDESK_EMAIL', 'helpdesk@xxx.xx.co');
define('CLIENT_REPLYTO_EMAIL', 'all@xxx.xx.co');
define('CLIENT_SMTP_CONFIG', Array(
	'protocol' => 'smtp',
	'smtp_host' => 'xx.xxx.com',
	'smtp_port' => 587,
	'smtp_user' => 'all@xxx.xx.co',
	'smtp_pass' => 'xxxxx',
	'charset'   => 'iso-8859-1',
	'clrf' => '\r\n',
	'newline' => '\r\n'
));
```
