### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by petrukkyaipethel** [TIKAJHQ/tiket#6]
[
![2020-10-06_11-13](https://user-images.githubusercontent.com/72428762/95159145-810e0c80-07c7-11eb-8f1a-19dc31177cad.png)
](url)

Please Can You Help Me ? Thanks U ..

**Comment by eksha** [comment]
@petrukkyaipethel The fix patch for this issue has been merged, please let us know if you face any other issue.

**Comment by petrukkyaipethel** [comment]
Thank you very much ...
